2021-04-28 14:38:20,380 INFO    MainThread:13887 [wandb_setup.py:_flush():69] setting env: {}
2021-04-28 14:38:20,380 INFO    MainThread:13887 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-28 14:38:20,382 INFO    MainThread:13887 [wandb_init.py:_log_setup():336] Logging user logs to /home/ubuntuadm/trainseg/utils/wandb/run-20210428_143820-qcnab6ex/logs/debug.log
2021-04-28 14:38:20,425 INFO    MainThread:13887 [wandb_init.py:_log_setup():337] Logging internal logs to /home/ubuntuadm/trainseg/utils/wandb/run-20210428_143820-qcnab6ex/logs/debug-internal.log
2021-04-28 14:38:20,425 INFO    MainThread:13887 [wandb_init.py:init():369] calling init triggers
2021-04-28 14:38:20,425 INFO    MainThread:13887 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-04-28 14:38:20,425 INFO    MainThread:13887 [wandb_init.py:init():418] starting backend
2021-04-28 14:38:20,425 INFO    MainThread:13887 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-28 14:38:20,438 INFO    MainThread:13887 [backend.py:ensure_launched():123] starting backend process...
2021-04-28 14:38:20,447 INFO    MainThread:13887 [backend.py:ensure_launched():127] started backend process with pid: 13901
2021-04-28 14:38:20,449 INFO    MainThread:13887 [wandb_init.py:init():423] backend started and connected
2021-04-28 14:38:20,451 INFO    MainThread:13887 [wandb_init.py:init():465] updated telemetry
2021-04-28 14:38:20,456 INFO    MainThread:13887 [wandb_init.py:init():484] communicating current version
2021-04-28 14:38:21,951 INFO    MainThread:13887 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.27 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-04-28 14:38:21,951 INFO    MainThread:13887 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-28 14:38:22,219 INFO    MainThread:13887 [wandb_init.py:init():522] starting run threads in backend
2021-04-28 14:38:22,771 WARNING MainThread:13887 [wandb_init.py:init():764] interrupted
Traceback (most recent call last):
  File "/home/ubuntuadm/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/home/ubuntuadm/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 525, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/ubuntuadm/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 783, in communicate_run_start
    result = self._communicate(rec)
  File "/home/ubuntuadm/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 533, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/ubuntuadm/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
